"use client";
import Link from "next/link";
import {FormEvent,useState} from "react";
import {apiError,authHeaders} from "../inventory/client";
type ImportRow={row_number:number;source_data:Record<string,unknown>;normalized_data:Record<string,unknown>;errors:{field:string;code:string}[];target_id:string|null};
type Batch={id:string;import_type:string;status:string;source_name:string;total_rows:number;valid_rows:number;error_rows:number;committed_transaction_id:string|null;rows:ImportRow[]};
export default function Imports(){
 const [kind,setKind]=useState("PRODUCT"),[source,setSource]=useState("manual.json"),[raw,setRaw]=useState('[{"sku":"SKU-001","name":"Example","base_unit_code":"EA"}]');
 const [batch,setBatch]=useState<Batch|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function request(path:string,method="GET",body?:unknown){const h=authHeaders();if(!h)throw new Error("กรุณาเข้าสู่ระบบ");const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/imports${path}`,{method,headers:{...h,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok)throw new Error(await apiError(r));return r.json()}
 async function refresh(id:string){setBatch((await request(`/${id}`)).data)}
 async function upload(e:FormEvent){e.preventDefault();setError("");setBusy(true);try{const rows=JSON.parse(raw);if(!Array.isArray(rows)||!rows.length)throw new Error("Rows must be a non-empty JSON array");const x=await request("","POST",{import_type:kind,source_name:source,rows});await refresh(x.data.id)}catch(e){setError(e instanceof Error?e.message:"Import failed")}finally{setBusy(false)}}
 async function action(name:"validate"|"commit"){if(!batch)return;setError("");setBusy(true);try{await request(`/${batch.id}/${name}`,"POST");await refresh(batch.id)}catch(e){setError(e instanceof Error?e.message:"Import failed")}finally{setBusy(false)}}
 return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">DATA · CONTROLLED IMPORT</p><h1>Imports</h1><p>Stage, validate and explicitly commit tenant-scoped product or opening-stock data. Validation never changes business data.</p></div><Link className="button secondary" href="/">Operations</Link></div>
 <form className="posting-form" onSubmit={upload}><div className="form-grid"><label>Import type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="PRODUCT">Products</option><option value="OPENING_STOCK">Opening stock</option></select></label><label>Source name<input required value={source} onChange={e=>setSource(e.target.value)}/></label><label className="wide">Rows (JSON array)<textarea className="import-textarea" required value={raw} onChange={e=>setRaw(e.target.value)}/></label></div><div className="form-actions"><button className="button" disabled={busy}>Stage batch</button><span className="hint">Preview and validation are side-effect free.</span></div></form>
 {error&&<div className="state error">{error}</div>}{batch&&<section className="panel import-result"><div className="panel-head"><div><h2>{batch.import_type} · {batch.status}</h2><small className="mono">{batch.id}</small></div><div className="form-actions"><button className="button secondary" disabled={busy||batch.status==="COMMITTED"} onClick={()=>action("validate")}>Validate</button><button className="button" disabled={busy||batch.status!=="READY_TO_COMMIT"} onClick={()=>action("commit")}>Commit</button></div></div><div className="metrics"><div className="metric"><span>Total</span><strong>{batch.total_rows}</strong></div><div className="metric"><span>Valid</span><strong>{batch.valid_rows}</strong></div><div className="metric"><span>Errors</span><strong>{batch.error_rows}</strong></div></div><div className="table-wrap"><table><thead><tr><th>Row</th><th>Normalized</th><th>Errors</th><th>Target</th></tr></thead><tbody>{batch.rows.map(r=><tr key={r.row_number}><td>{r.row_number}</td><td><small className="mono">{JSON.stringify(r.normalized_data)}</small></td><td>{r.errors.length?r.errors.map(x=>`${x.field}:${x.code}`).join(", "):<span className="badge">VALID</span>}</td><td><small className="mono">{r.target_id??"—"}</small></td></tr>)}</tbody></table></div></section>}</main>
}