"use client";
import Link from "next/link";import {FormEvent,useState} from "react";import {apiError,authHeaders} from "../client";
type Batch={id:string;status:string;valid_rows?:number;error_rows?:number;rows?:Array<{row_number:number;errors:Array<{field:string;code:string}>}>};
export default function Imports(){const [kind,setKind]=useState("PRODUCT"),[source,setSource]=useState(""),[batch,setBatch]=useState<Batch|null>(null),[error,setError]=useState("");
async function call(path:string,method="POST",body?:unknown){const h=authHeaders();if(!h){setError("กรุณาเข้าสู่ระบบ");return null}const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/imports${path}`,{method,headers:{...h,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok){setError(await apiError(r));return null}return (await r.json()).data}
async function upload(e:FormEvent){e.preventDefault();setError("");try{const rows=JSON.parse(source) as Record<string,unknown>[];const d=await call("","POST",{import_type:kind,source_name:"web-json-import.json",rows});if(d){setBatch(d);const v=await call(`/${d.id}/validate`);if(v){const detail=await call(`/${d.id}`,"GET");setBatch({...v,...detail})}}}catch{setError("ข้อมูลต้องเป็น JSON array ที่ถูกต้อง")}}
async function commit(){if(!batch)return;const d=await call(`/${batch.id}/commit`);if(d)setBatch(d)}
return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">INVENTORY · CONTROLLED IMPORT</p><h1>Product & Opening Stock Import</h1><p>Stage → validate → preview → explicit atomic commit. Opening stock posts through the inventory ledger only.</p></div><Link className="button secondary" href="/inventory/operations">Operations</Link></div>
<form className="posting-form" onSubmit={upload}><div className="form-grid"><label>Import type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="PRODUCT">Product</option><option value="OPENING_STOCK">Opening stock</option></select></label><label className="wide">Rows as JSON array<textarea rows={12} value={source} onChange={e=>setSource(e.target.value)} placeholder={kind==="PRODUCT"?'[{"sku":"SKU-1","name":"Item","base_unit_code":"EA"}]':'[{"legal_entity_code":"HQ","sku":"SKU-1","unit_code":"EA","warehouse_code":"MAIN","location_code":"A1","quantity":"10"}]'} /></label></div><div className="form-actions"><button className="button" type="submit">Stage & validate</button></div></form>
{error&&<div className="state error">{error}</div>}{batch&&<section className="panel"><div className="panel-head"><h2>Preview</h2><span className="badge">{batch.status}</span></div><div className="state compact"><p className="mono">{batch.id}</p><p>Valid: {batch.valid_rows??"—"} · Errors: {batch.error_rows??"—"}</p>{batch.rows?.filter(x=>x.errors.length).map(x=><p key={x.row_number}>Row {x.row_number}: {x.errors.map(e=>`${e.field} ${e.code}`).join(", ")}</p>)}{batch.status==="READY_TO_COMMIT"&&<button className="button" onClick={commit}>Commit atomically</button>}</div></section>}</main>}
