"use client";
import Link from "next/link";import {FormEvent,useCallback,useEffect,useState} from "react";
type Row={id:string;warehouse_id:string;code:string;name:string;location_type:string;allow_stock:boolean;status:string};type Warehouse={id:string;code:string;name:string;status:string};
function auth(){const token=sessionStorage.getItem("nomos_session"),tenant=sessionStorage.getItem("nomos_tenant");return token&&tenant?{Authorization:`Bearer ${token}`,"X-Tenant-ID":tenant}:null}
export default function Page(){const [rows,setRows]=useState<Row[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[warehouse,setWarehouse]=useState(""),[code,setCode]=useState(""),[name,setName]=useState(""),[locationType,setLocationType]=useState("STORAGE"),[allowStock,setAllowStock]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Row|null>(null);
 const load=useCallback(async()=>{const h=auth();if(!h){setError("กรุณาเข้าสู่ระบบก่อนใช้งาน Master Data");return}const [l,w]=await Promise.all([fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/locations`,{headers:h}),fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/warehouses?status=ACTIVE`,{headers:h})]);if(!l.ok||!w.ok){setError("โหลดข้อมูลไม่สำเร็จ");return}const lb=await l.json(),wb=await w.json();setRows(lb.data);setWarehouses(wb.data);setWarehouse(x=>x||wb.data[0]?.id||"");setError("")},[]);
 useEffect(()=>{queueMicrotask(()=>void load())},[load]);
 function edit(r:Row){setEditing(r);setWarehouse(r.warehouse_id);setCode(r.code);setName(r.name);setLocationType(r.location_type);setAllowStock(r.allow_stock);setError("")}
 function reset(){setEditing(null);setCode("");setName("");setLocationType("STORAGE");setAllowStock(true)}
 async function create(e:FormEvent){e.preventDefault();const h=auth();if(!h||!warehouse)return;setBusy(true);const url=editing?`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/location/${editing.id}`:`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/locations`;const r=await fetch(url,{method:editing?"PUT":"POST",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({warehouse_id:warehouse,code:code.trim(),name:name.trim(),location_type:locationType,allow_stock:allowStock})});setBusy(false);if(!r.ok){setError("สร้าง Location ไม่สำเร็จ");return}reset();await load()}
 async function archive(id:string){const h=auth();if(!h||!confirm("Archive this location?"))return;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/location/${id}/archive`,{method:"POST",headers:h});if(!r.ok){setError("Archive Location ไม่สำเร็จ");return}await load()}
 return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">MASTER DATA</p><h1>Locations</h1><p>Warehouse locations and stock policy.</p></div><Link className="button" href="/">Overview</Link></div><form className="filterbar" onSubmit={create}><label>Warehouse<select required value={warehouse} onChange={e=>setWarehouse(e.target.value)}>{warehouses.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Code<input required maxLength={64} value={code} onChange={e=>setCode(e.target.value)}/></label><label>Name<input required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label>Type<select value={locationType} onChange={e=>setLocationType(e.target.value)}><option>STORAGE</option><option>RECEIVING</option><option>SHIPPING</option><option>QUARANTINE</option></select></label><label><input type="checkbox" checked={allowStock} onChange={e=>setAllowStock(e.target.checked)}/> Allow stock</label><button className="button" disabled={busy||!warehouse}>{busy?"Saving…":editing?"Save Location":"Create Location"}</button>{editing&&<button type="button" className="button secondary" onClick={reset}>Cancel</button>}</form>
 {error&&<div className="state error" role="alert">{error}</div>} {!error&&rows.length===0?<div className="state">No records found.</div>:<div className="table-wrap"><table><thead><tr><th>Warehouse</th><th>Code</th><th>Name</th><th>Location Type</th><th>Allow Stock</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{warehouses.find(w=>w.id===r.warehouse_id)?.code??r.warehouse_id.slice(0,8)}</td><td>{r.code}</td><td>{r.name}</td><td>{r.location_type}</td><td>{r.allow_stock?"Yes":"No"}</td><td>{r.status}</td><td>{r.status==="ACTIVE"?<><button type="button" onClick={()=>edit(r)}>Edit</button> <button type="button" onClick={()=>void archive(r.id)}>Archive</button></>:"—"}</td></tr>)}</tbody></table></div>}</main>}