"use client";
import {useCallback,useEffect,useState} from "react";
import {apiError,authHeaders} from "../inventory/client";
type Account={id:string;legal_entity_id:string;code:string;name:string;account_type:string;is_control:boolean;status:string};
export default function Finance(){const base=process.env.NEXT_PUBLIC_API_URL??"";const [rows,setRows]=useState<Account[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{const h=authHeaders();if(!h){setError("กรุณาเข้าสู่ระบบ");setLoading(false);return}const r=await fetch(base+"/api/v1/finance/accounts",{headers:h});setLoading(false);if(!r.ok){setError(await apiError(r));return}setRows((await r.json()).data)},[base]);useEffect(()=>{queueMicrotask(load)},[load]);
 return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">NOMOS ERP · FINANCE</p><h1>Finance & Accounting</h1><p>Legal-entity scoped chart of accounts, fiscal-period controls, immutable journals and AR/AP financial truth.</p></div></div>
 <div className="cards"><div className="card featured"><strong>Chart of Accounts</strong><span>{rows.length} configured accounts</span></div><div className="card"><strong>General Ledger</strong><span>Balanced posting with explicit reversal</span></div><div className="card"><strong>AR / AP</strong><span>Invoices, receipts, payments and allocations</span></div><div className="card"><strong>Controls</strong><span>Closed-period and idempotent source posting</span></div></div>
 {error&&<div className="state error">{error}</div>}{loading?<div className="state">Loading finance…</div>:<section className="panel"><h2>Chart of Accounts</h2>{rows.length===0?<div className="state">No accounts configured.</div>:<div className="table-wrap"><table><thead><tr><th>Code</th><th>Name</th><th>Type</th><th>Control</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td className="mono">{x.code}</td><td>{x.name}</td><td>{x.account_type}</td><td>{x.is_control?"Yes":"No"}</td><td>{x.status}</td></tr>)}</tbody></table></div>}</section>}</main>}
