"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {apiError,authHeaders} from "../inventory/client";
type Row=Record<string,unknown>;
const tabs=[["accounts","Chart of Accounts"],["periods","Fiscal Periods"],["journals","Journals / GL"],["invoices","AR / AP Invoices"],["payments","Receipts / Payments"]] as const;
export default function Finance(){const base=process.env.NEXT_PUBLIC_API_URL??"";const [tab,setTab]=useState("accounts"),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[entity,setEntity]=useState(""),[code,setCode]=useState(""),[name,setName]=useState(""),[kind,setKind]=useState("ASSET"),[period,setPeriod]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async(t=tab)=>{setLoading(true);setError("");const h=authHeaders();if(!h){setError("กรุณาเข้าสู่ระบบ");setLoading(false);return}const r=await fetch(base+"/api/v1/finance/"+t,{headers:h});setLoading(false);if(!r.ok){setError(await apiError(r));return}setRows((await r.json()).data)},[base,tab]);useEffect(()=>{queueMicrotask(()=>void load())},[load]);

 async function createAccount(e:FormEvent){e.preventDefault();const h=authHeaders();if(!h)return;setBusy(true);const r=await fetch(base+"/api/v1/finance/accounts",{method:"POST",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({legal_entity_id:entity,code,name,account_type:kind,currency_code:"THB",is_control:false})});setBusy(false);if(!r.ok){setError(await apiError(r));return}setCode("");setName("");await load("accounts")}
 async function createPeriod(e:FormEvent){e.preventDefault();const h=authHeaders();if(!h)return;setBusy(true);const r=await fetch(base+"/api/v1/finance/periods",{method:"POST",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({legal_entity_id:entity,period_key:period,start_date:start,end_date:end})});setBusy(false);if(!r.ok){setError(await apiError(r));return}setPeriod("");setStart("");setEnd("");await load("periods")}
 async function periodStatus(id:string,status:string){const h=authHeaders();if(!h)return;const r=await fetch(base+`/api/v1/finance/periods/${id}/${status}`,{method:"POST",headers:h});if(!r.ok){setError(await apiError(r));return}await load("periods")}
 const keys=rows.length?Object.keys(rows[0]).filter(k=>!["tenant_id"].includes(k)).slice(0,7):[];
 return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">Finance & Accounting</p><h1>Financial operations</h1><p>Accounting-owned financial truth: periods, immutable journals, AR/AP documents and settlement.</p></div></div>
 <div className="section-nav">{tabs.map(([id,label])=><button className={tab===id?"tab active":"tab"} key={id} onClick={()=>{setTab(id);void load(id)}}>{label}</button>)}</div>
 <div className="metrics"><div className="metric"><span>Workspace</span><strong>{tabs.find(x=>x[0]===tab)?.[1]}</strong></div><div className="metric"><span>Records</span><strong>{rows.length}</strong></div><div className="metric"><span>Posting rule</span><strong>Immutable</strong></div></div>
 {tab==="accounts"&&<form className="inline-form" onSubmit={createAccount}><input required value={entity} onChange={e=>setEntity(e.target.value)} placeholder="Legal entity ID"/><input required value={code} onChange={e=>setCode(e.target.value)} placeholder="Account code"/><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Account name"/><select value={kind} onChange={e=>setKind(e.target.value)}><option>ASSET</option><option>LIABILITY</option><option>EQUITY</option><option>REVENUE</option><option>EXPENSE</option></select><button className="button" disabled={busy}>Create account</button></form>}
 {tab==="periods"&&<form className="inline-form" onSubmit={createPeriod}><input required value={entity} onChange={e=>setEntity(e.target.value)} placeholder="Legal entity ID"/><input required value={period} onChange={e=>setPeriod(e.target.value)} placeholder="Period key"/><input required type="date" value={start} onChange={e=>setStart(e.target.value)}/><input required type="date" value={end} onChange={e=>setEnd(e.target.value)}/><button className="button" disabled={busy}>Create period</button></form>}
 {error&&<div className="state error">{error}</div>}{loading?<div className="state">Loading finance…</div>:<section className="panel"><div className="panel-head"><h2>{tabs.find(x=>x[0]===tab)?.[1]}</h2><span className="hint">Tenant scoped</span></div>{rows.length===0?<div className="state compact">No records configured.</div>:<div className="table-wrap"><table><thead><tr>{keys.map(k=><th key={k}>{k.replaceAll("_"," ")}</th>)}{tab==="periods"&&<th>Actions</th>}</tr></thead><tbody>{rows.map((x,i)=><tr key={String(x.id??i)}>{keys.map(k=><td key={k} className={k.includes("amount")||k.includes("balance")?"quantity":k.endsWith("_id")?"mono":""}>{String(x[k]??"—")}</td>)}{tab==="periods"&&<td><button type="button" onClick={()=>void periodStatus(String(x.id),"CLOSED")}>Close</button> <button type="button" onClick={()=>void periodStatus(String(x.id),"OPEN")}>Open</button></td>}</tr>)}</tbody></table></div>}</section>}</main>}