"use client";
import {useCallback,useEffect,useState} from "react";
import {apiError,authHeaders} from "../inventory/client";
type Row=Record<string,unknown>;
const tabs=[["accounts","Chart of Accounts"],["periods","Fiscal Periods"],["journals","Journals / GL"],["invoices","AR / AP Invoices"],["payments","Receipts / Payments"]] as const;
export default function Finance(){const base=process.env.NEXT_PUBLIC_API_URL??"";const [tab,setTab]=useState("accounts"),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=useCallback(async(t=tab)=>{setLoading(true);setError("");const h=authHeaders();if(!h){setError("กรุณาเข้าสู่ระบบ");setLoading(false);return}const r=await fetch(base+"/api/v1/finance/"+t,{headers:h});setLoading(false);if(!r.ok){setError(await apiError(r));return}setRows((await r.json()).data)},[base,tab]);useEffect(()=>{queueMicrotask(()=>void load())},[load]);
 const keys=rows.length?Object.keys(rows[0]).filter(k=>!["tenant_id"].includes(k)).slice(0,7):[];
 return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">Finance & Accounting</p><h1>Financial operations</h1><p>Accounting-owned financial truth: periods, immutable journals, AR/AP documents and settlement.</p></div></div>
 <div className="section-nav">{tabs.map(([id,label])=><button className={tab===id?"tab active":"tab"} key={id} onClick={()=>{setTab(id);void load(id)}}>{label}</button>)}</div>
 <div className="metrics"><div className="metric"><span>Workspace</span><strong>{tabs.find(x=>x[0]===tab)?.[1]}</strong></div><div className="metric"><span>Records</span><strong>{rows.length}</strong></div><div className="metric"><span>Posting rule</span><strong>Immutable</strong></div></div>
 {error&&<div className="state error">{error}</div>}{loading?<div className="state">Loading finance…</div>:<section className="panel"><div className="panel-head"><h2>{tabs.find(x=>x[0]===tab)?.[1]}</h2><span className="hint">Tenant scoped</span></div>{rows.length===0?<div className="state compact">No records configured.</div>:<div className="table-wrap"><table><thead><tr>{keys.map(k=><th key={k}>{k.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((x,i)=><tr key={String(x.id??i)}>{keys.map(k=><td key={k} className={k.includes("amount")||k.includes("balance")?"quantity":k.endsWith("_id")?"mono":""}>{String(x[k]??"—")}</td>)}</tr>)}</tbody></table></div>}</section>}</main>}