"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {apiError,authHeaders} from "../inventory/client";
type Lead={id:string;lead_number:string;name:string;company_name:string|null;status:string;source:string|null};
type Opp={id:string;opportunity_number:string;name:string;status:string;currency_code:string;estimated_amount:string};
export default function CRM(){
 const [leads,setLeads]=useState<Lead[]>([]),[opps,setOpps]=useState<Opp[]>([]);
 const [number,setNumber]=useState(""),[name,setName]=useState(""),[company,setCompany]=useState("");
 const [oppNumber,setOppNumber]=useState(""),[oppName,setOppName]=useState(""),[oppAmount,setOppAmount]=useState("0"),[oppLead,setOppLead]=useState("");
 const [activityType,setActivityType]=useState("NOTE"),[activitySubject,setActivitySubject]=useState(""),[activityLead,setActivityLead]=useState("");
 const [error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const h=authHeaders();if(!h){setError("กรุณาเข้าสู่ระบบ");return}const [l,o]=await Promise.all([fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/crm/leads`,{headers:h}),fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/crm/opportunities`,{headers:h})]);if(!l.ok){setError(await apiError(l));return}if(!o.ok){setError(await apiError(o));return}setLeads((await l.json()).data);setOpps((await o.json()).data);setError("")}
 useEffect(()=>{queueMicrotask(load)},[]);
 async function createLead(e:FormEvent){e.preventDefault();const h=authHeaders();if(!h)return;setBusy(true);const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/crm/leads`,{method:"POST",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({lead_number:number.trim(),name:name.trim(),company_name:company.trim()||null})});setBusy(false);if(!r.ok){setError(await apiError(r));return}setNumber("");setName("");setCompany("");await load()}
 async function createOpportunity(e:FormEvent){e.preventDefault();const h=authHeaders();if(!h)return;setBusy(true);const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/crm/opportunities`,{method:"POST",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({opportunity_number:oppNumber.trim(),name:oppName.trim(),lead_id:oppLead||null,currency_code:"THB",estimated_amount:oppAmount||"0"})});setBusy(false);if(!r.ok){setError(await apiError(r));return}setOppNumber("");setOppName("");setOppAmount("0");setOppLead("");await load()}
 async function createActivity(e:FormEvent){e.preventDefault();const h=authHeaders();if(!h)return;setBusy(true);const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/crm/activities`,{method:"POST",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({activity_type:activityType,subject:activitySubject.trim(),lead_id:activityLead||null})});setBusy(false);if(!r.ok){setError(await apiError(r));return}setActivitySubject("");setActivityLead("");setError("")}
 async function transition(id:string,status:string){const h=authHeaders();if(!h)return;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/crm/leads/${id}/transition/${status}`,{method:"POST",headers:h});if(!r.ok){setError(await apiError(r));return}await load()}
 return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">SALES · CRM FOUNDATION</p><h1>CRM Pipeline</h1><p>Lead qualification, opportunities and customer activities.</p></div><Link className="button secondary" href="/partners">Partners</Link></div>
 <form className="inline-form" onSubmit={createLead}><input required value={number} onChange={e=>setNumber(e.target.value)} placeholder="Lead number"/><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Contact name"/><input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Company"/><button className="button" disabled={busy}>Create lead</button></form>
 <form className="inline-form" onSubmit={createOpportunity}><input required value={oppNumber} onChange={e=>setOppNumber(e.target.value)} placeholder="Opportunity number"/><input required value={oppName} onChange={e=>setOppName(e.target.value)} placeholder="Opportunity name"/><input type="number" min="0" step="0.01" value={oppAmount} onChange={e=>setOppAmount(e.target.value)} placeholder="Amount"/><select value={oppLead} onChange={e=>setOppLead(e.target.value)}><option value="">No lead</option>{leads.map(x=><option key={x.id} value={x.id}>{x.lead_number} · {x.name}</option>)}</select><button className="button" disabled={busy}>Create opportunity</button></form>
 <form className="inline-form" onSubmit={createActivity}><select value={activityType} onChange={e=>setActivityType(e.target.value)}><option>NOTE</option><option>CALL</option><option>MEETING</option><option>EMAIL</option></select><input required value={activitySubject} onChange={e=>setActivitySubject(e.target.value)} placeholder="Activity subject"/><select value={activityLead} onChange={e=>setActivityLead(e.target.value)}><option value="">General activity</option>{leads.map(x=><option key={x.id} value={x.id}>{x.lead_number} · {x.name}</option>)}</select><button className="button" disabled={busy}>Add activity</button></form>
 {error&&<div className="state error" role="alert">{error}</div>}
 <div className="split"><section className="panel"><div className="panel-head"><h2>Leads</h2></div><div className="movement-list">{leads.length===0?<div className="state">No leads found.</div>:leads.map(x=><div className="list-button" key={x.id}><span className="badge">{x.status}</span><span><strong>{x.lead_number} · {x.name}</strong><small>{x.company_name??"Individual"} · {x.source??"Direct"}</small></span>{x.status==="OPEN"&&<button className="button secondary" onClick={()=>void transition(x.id,"QUALIFIED")}>Qualify</button>}{x.status==="QUALIFIED"&&<button className="button secondary" onClick={()=>void transition(x.id,"WON")}>Won</button>}</div>)}</div></section>
 <section className="panel"><div className="panel-head"><h2>Opportunities</h2></div><div className="movement-list">{opps.length===0?<div className="state">No opportunities found.</div>:opps.map(x=><div className="list-button" key={x.id}><span className="badge">{x.status}</span><span><strong>{x.opportunity_number} · {x.name}</strong><small>{x.currency_code} {x.estimated_amount}</small></span></div>)}</div></section></div></main>
}