"use client";
import Link from "next/link";import {FormEvent,useEffect,useState} from "react";import {apiError,authHeaders} from "../inventory/client";
type Lead={id:string;lead_number:string;name:string;company_name:string|null;status:string;source:string|null};type Opp={id:string;opportunity_number:string;name:string;status:string;currency_code:string;estimated_amount:string};
export default function CRM(){const [leads,setLeads]=useState<Lead[]>([]);const [opps,setOpps]=useState<Opp[]>([]);const [number,setNumber]=useState("");const [name,setName]=useState("");const [company,setCompany]=useState("");const [error,setError]=useState("");
async function load(){const h=authHeaders();if(!h){setError("กรุณาเข้าสู่ระบบ");return}const [l,o]=await Promise.all([fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/crm/leads`,{headers:h}),fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/crm/opportunities`,{headers:h})]);if(l.ok)setLeads((await l.json()).data);else setError(await apiError(l));if(o.ok)setOpps((await o.json()).data)}
useEffect(()=>{queueMicrotask(load)},[]);
async function create(e:FormEvent){e.preventDefault();const h=authHeaders();if(!h)return;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/crm/leads`,{method:"POST",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({lead_number:number,name,company_name:company||null})});if(!r.ok){setError(await apiError(r));return}setNumber("");setName("");setCompany("");await load()}
async function transition(id:string,status:string){const h=authHeaders();if(!h)return;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/crm/leads/${id}/transition/${status}`,{method:"POST",headers:h});if(!r.ok){setError(await apiError(r));return}await load()}
return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">SALES · CRM FOUNDATION</p><h1>CRM Pipeline</h1><p>Lead and opportunity history before Quotation and Sales Order are introduced in Phase 9.</p></div><Link className="button secondary" href="/partners">Partners</Link></div>
<form className="inline-form" onSubmit={create}><input required value={number} onChange={e=>setNumber(e.target.value)} placeholder="Lead number"/><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Contact name"/><input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Company"/><button className="button">Create lead</button></form>{error&&<div className="state error">{error}</div>}
<div className="split"><section className="panel"><div className="panel-head"><h2>Leads</h2></div><div className="movement-list">{leads.map(x=><div className="list-button" key={x.id}><span className="badge">{x.status}</span><span><strong>{x.lead_number} · {x.name}</strong><small>{x.company_name??"Individual"} · {x.source??"Direct"}</small></span>{x.status==="OPEN"&&<button className="button secondary" onClick={()=>transition(x.id,"QUALIFIED")}>Qualify</button>}{x.status==="QUALIFIED"&&<button className="button secondary" onClick={()=>transition(x.id,"WON")}>Won</button>}</div>)}</div></section>
<section className="panel"><div className="panel-head"><h2>Opportunities</h2></div><div className="movement-list">{opps.map(x=><div className="list-button" key={x.id}><span className="badge">{x.status}</span><span><strong>{x.opportunity_number} · {x.name}</strong><small>{x.currency_code} {x.estimated_amount}</small></span></div>)}</div></section></div></main>}