"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {apiError,authHeaders,newIdempotencyKey} from "../client";
type Row={id:string;transaction_type:string;status:string;source_type:string|null;source_number:string|null;reference:string|null;reason:string|null;reversal_of_id:string|null;reversed_by_id:string|null;posted_at:string};
export default function Movements(){const [rows,setRows]=useState<Row[]>([]);const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState<string|null>(null);
 async function load(){const headers=authHeaders();if(!headers){setError("กรุณาเข้าสู่ระบบก่อนใช้งาน Inventory");return}const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/inventory/transactions`,{headers});if(!r.ok){setError(await apiError(r));return}setRows((await r.json()).data as Row[])}
 useEffect(()=>{queueMicrotask(load)},[]);
 async function reverse(row:Row){const reason=window.prompt("Reason for reversal");if(!reason?.trim())return;const headers=authHeaders();if(!headers){setError("กรุณาเข้าสู่ระบบใหม่");return}setBusy(row.id);setError("");setMessage("");try{const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/inventory/transactions/${row.id}/reverse`,{method:"POST",headers:{...headers,"Content-Type":"application/json","Idempotency-Key":newIdempotencyKey("reversal")},body:JSON.stringify({reason:reason.trim()})});if(!r.ok){setError(await apiError(r));return}setMessage("Reversal posted");await load()}finally{setBusy(null)}}
 return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">INVENTORY · LEDGER</p><h1>Movements</h1><p>Immutable posted inventory history. Corrections use explicit linked reversals.</p></div><Link className="button secondary" href="/inventory">Inventory</Link></div>{error&&<div className="state error" role="alert">{error}</div>}{message&&<div className="state success" role="status">{message}</div>}<div className="table-wrap"><table><thead><tr><th>Type</th><th>Reference</th><th>Source</th><th>Posted</th><th>Status</th><th>Link</th><th>Action</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><span className="badge">{x.transaction_type}</span></td><td>{x.reference??"—"}</td><td>{x.source_type?x.source_type+" · "+(x.source_number??"—"):"—"}</td><td>{new Date(x.posted_at).toLocaleString()}</td><td>{x.status}</td><td className="mono">{(x.reversal_of_id??x.reversed_by_id)?.slice(0,8)??"—"}</td><td>{x.status==="POSTED"&&!x.reversal_of_id&&!x.reversed_by_id?<button type="button" disabled={busy===x.id} onClick={()=>void reverse(x)}>{busy===x.id?"Reversing…":"Reverse"}</button>:"—"}</td></tr>)}</tbody></table></div></main>}
