"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
type Row={id:string;code:string;name:string;symbol:string|null;precision:number;status:string};
function auth(){const token=sessionStorage.getItem("nomos_session");const tenant=sessionStorage.getItem("nomos_tenant");return token&&tenant?{Authorization:`Bearer ${token}`,"X-Tenant-ID":tenant}:null}
export default function Page(){
 const [rows,setRows]=useState<Row[]>([]),[code,setCode]=useState(""),[name,setName]=useState(""),[symbol,setSymbol]=useState(""),[precision,setPrecision]=useState(0),[error,setError]=useState(""),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Row|null>(null);
 const load=useCallback(async()=>{const headers=auth();if(!headers){setError("กรุณาเข้าสู่ระบบก่อนใช้งาน Master Data");return}const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/units`,{headers});if(!r.ok){setError("โหลดข้อมูลไม่สำเร็จ");return}setRows((await r.json()).data as Row[]);setError("")},[]);
 useEffect(()=>{queueMicrotask(()=>void load())},[load]);
 function edit(row:Row){setEditing(row);setCode(row.code);setName(row.name);setSymbol(row.symbol??"");setPrecision(row.precision);setError("")}
 function reset(){setEditing(null);setCode("");setName("");setSymbol("");setPrecision(0)}
 async function archive(id:string){const headers=auth();if(!headers)return;if(!confirm("Archive this unit?"))return;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/unit/${id}/archive`,{method:"POST",headers});if(!r.ok){setError("Archive Unit ไม่สำเร็จ");return}await load()}
 async function create(e:FormEvent){e.preventDefault();const headers=auth();if(!headers)return;setBusy(true);setError("");const url=editing?`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/unit/${editing.id}`:`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/units`;const r=await fetch(url,{method:editing?"PUT":"POST",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({code:code.trim(),name:name.trim(),symbol:symbol.trim()||null,precision})});setBusy(false);if(!r.ok){setError(r.status===409?"Unit code already exists.":"สร้าง Unit ไม่สำเร็จ");return}reset();await load()}
 return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">MASTER DATA</p><h1>Units</h1><p>Tenant-scoped units of measure.</p></div><Link className="button" href="/">Overview</Link></div>
 <form className="filterbar" onSubmit={create}><label>Code<input required maxLength={32} value={code} onChange={e=>setCode(e.target.value)}/></label><label>Name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Symbol<input maxLength={24} value={symbol} onChange={e=>setSymbol(e.target.value)}/></label><label>Precision<input type="number" min={0} max={8} value={precision} onChange={e=>setPrecision(Number(e.target.value))}/></label><button className="button" disabled={busy} type="submit">{busy?"Saving…":editing?"Save Unit":"Create Unit"}</button>{editing&&<button className="button secondary" type="button" onClick={reset}>Cancel</button>}</form>
 {error&&<div className="state error" role="alert">{error}</div>}{!error&&rows.length===0?<div className="state">No records found.</div>:<div className="table-wrap"><table><thead><tr><th>Code</th><th>Name</th><th>Symbol</th><th>Precision</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.code}</td><td>{r.name}</td><td>{r.symbol??"—"}</td><td>{r.precision}</td><td>{r.status}</td><td>{r.status==="ACTIVE"&&<><button className="button secondary" type="button" onClick={()=>edit(r)}>Edit</button> <button className="button secondary" type="button" onClick={()=>void archive(r.id)}>Archive</button></>}</td></tr>)}</tbody></table></div>}</main>
}