"use client";
import Link from "next/link";import {FormEvent,useEffect,useState} from "react";import {apiError,authHeaders,newIdempotencyKey} from "../client";
type Count={id:string;count_number:string;status:string;warehouse_code:string;warehouse_name:string;line_count:number;counted_lines:number;variance_quantity:string};
type Warehouse={id:string;legal_entity_id:string;code:string;name:string};
type Detail={id:string;count_number:string;status:string;lines:{id:string;sku:string;product_name:string;location_code:string;system_quantity:string;counted_quantity:string|null;variance:string|null}[]};
export default function Counts(){const [rows,setRows]=useState<Count[]>([]);const [warehouses,setWarehouses]=useState<Warehouse[]>([]);const [selected,setSelected]=useState<Detail|null>(null);const [warehouse,setWarehouse]=useState("");const [number,setNumber]=useState("");const [error,setError]=useState("");
async function load(){const h=authHeaders();if(!h)return;const [c,w]=await Promise.all([fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/inventory/operations/stock-counts`,{headers:h}),fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/warehouses?status=ACTIVE&limit=200`,{headers:h})]);if(c.ok)setRows((await c.json()).data as Count[]);if(w.ok)setWarehouses((await w.json()).data as Warehouse[])}
useEffect(()=>{queueMicrotask(load)},[]);
async function create(e:FormEvent){e.preventDefault();setError("");const h=authHeaders();const w=warehouses.find(x=>x.id===warehouse);if(!h||!w)return;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/inventory/operations/stock-counts`,{method:"POST",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({legal_entity_id:w.legal_entity_id,warehouse_id:w.id,count_number:number})});if(!r.ok){setError(await apiError(r));return}setNumber("");await load()}
async function open(id:string){const h=authHeaders();if(!h)return;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/inventory/operations/stock-counts/${id}`,{headers:h});if(r.ok)setSelected((await r.json()).data as Detail)}
async function save(){if(!selected)return;const h=authHeaders();if(!h)return;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/inventory/operations/stock-counts/${selected.id}/counts`,{method:"PUT",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({lines:selected.lines.map(x=>({line_id:x.id,counted_quantity:x.counted_quantity}))})});if(!r.ok){setError(await apiError(r));return}await open(selected.id);await load()}
async function post(){if(!selected)return;const h=authHeaders();if(!h)return;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/inventory/operations/stock-counts/${selected.id}/post`,{method:"POST",headers:{...h,"Idempotency-Key":newIdempotencyKey("COUNT")}});if(!r.ok){setError(await apiError(r));return}await open(selected.id);await load()}
return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">INVENTORY · STOCK COUNT</p><h1>Stock Counts</h1><p>Freeze a system snapshot, enter physical counts, then post only the variance through Inventory ADJUST.</p></div><Link className="button secondary" href="/inventory/operations">Operations</Link></div>
<form className="inline-form" onSubmit={create}><select required value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option value="">Warehouse</option>{warehouses.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><input required value={number} onChange={e=>setNumber(e.target.value)} placeholder="Count number"/><button className="button">Create count</button></form>{error&&<div className="state error">{error}</div>}
<div className="split"><section className="panel"><div className="panel-head"><h2>Documents</h2></div><div className="movement-list">{rows.map(x=><button className="list-button" key={x.id} onClick={()=>open(x.id)}><span className="badge">{x.status}</span><span><strong>{x.count_number}</strong><small>{x.warehouse_code} · {x.counted_lines}/{x.line_count} · variance {x.variance_quantity}</small></span></button>)}</div></section>
<section className="panel"><div className="panel-head"><h2>{selected?.count_number??"Select a count"}</h2></div>{selected&&<><div className="count-lines">{selected.lines.map((x,i)=><label key={x.id}><span><strong>{x.sku}</strong><small>{x.product_name} · {x.location_code} · system {x.system_quantity}</small></span><input disabled={selected.status==="POSTED"} inputMode="decimal" value={x.counted_quantity??""} onChange={e=>setSelected({...selected,lines:selected.lines.map((line,j)=>j===i?{...line,counted_quantity:e.target.value}:line)})}/></label>)}</div>{selected.status!=="POSTED"&&<div className="form-actions"><button className="button secondary" onClick={save}>Save counts</button><button className="button" disabled={selected.lines.some(x=>x.counted_quantity===null||x.counted_quantity==="")} onClick={post}>Post variance</button></div>}</>}</section></div></main>}