"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {apiError,authHeaders,newIdempotencyKey} from "../inventory/client";
type Q={id:string;quotation_number:string;customer_id:string;status:string;current_revision:number;total_amount:string;currency_code:string};
type O={id:string;order_number:string;status:string;source_quotation_id:string;source_quotation_revision:number};
type L={id:string;line_number:number;ordered_quantity:string;reserved_quantity:string;delivered_quantity:string;returned_quantity:string};
export default function Sales(){
 const [quotes,setQuotes]=useState<Q[]>([]),[orders,setOrders]=useState<O[]>([]),[lines,setLines]=useState<L[]>([]);
 const [selected,setSelected]=useState(""),[location,setLocation]=useState(""),[line,setLine]=useState(""),[qty,setQty]=useState("");
 const [error,setError]=useState(""),[message,setMessage]=useState("");const base=process.env.NEXT_PUBLIC_API_URL??"";
 const load=useCallback(async ()=>{const h=authHeaders();if(!h){setError("กรุณาเข้าสู่ระบบ");return}const [q,o]=await Promise.all([fetch(base+"/api/v1/sales/quotations",{headers:h}),fetch(base+"/api/v1/sales/orders",{headers:h})]);if(!q.ok||!o.ok){setError(await apiError(!q.ok?q:o));return}setQuotes((await q.json()).data);setOrders((await o.json()).data)},[base]);
 useEffect(()=>{queueMicrotask(load)},[load]);
 async function choose(id:string){setSelected(id);const h=authHeaders();if(!h)return;const r=await fetch(base+"/api/v1/sales/orders/"+id+"/lines",{headers:h});if(!r.ok){setError(await apiError(r));return}setLines((await r.json()).data)}
 async function movement(kind:"reserve"|"deliveries"|"returns"){setError("");setMessage("");const h=authHeaders();if(!h||!selected||!line)return;const headers:Record<string,string>={...h,"Content-Type":"application/json"};if(kind!=="reserve")headers["Idempotency-Key"]=newIdempotencyKey(kind);const r=await fetch(base+"/api/v1/sales/orders/"+selected+"/"+kind,{method:"POST",headers,body:JSON.stringify({location_id:location,lines:[{sales_order_line_id:line,quantity:qty}]})});if(!r.ok){setError(await apiError(r));return}setMessage(kind==="reserve"?"Stock reserved":kind==="deliveries"?"Delivery posted":"Sales return posted");await load();await choose(selected)}
 return <main className="erp-main"><p className="eyebrow">NOMOS ERP · SALES & CRM</p><h1>Sales Operations</h1><p>Quotation acceptance is traceable to an exact revision. Reservation changes availability only; delivery and return commit physical stock through Inventory.</p>{error&&<p className="error" role="alert">{error}</p>}{message&&<p aria-live="polite">{message}</p>}
 <section className="panel"><div className="section-head"><h2>Quotation Pipeline</h2><Link href="/crm">CRM</Link></div><div className="table-wrap"><table><thead><tr><th>QT</th><th>Customer</th><th>Revision</th><th>Status</th><th>Total</th></tr></thead><tbody>{quotes.map(q=><tr key={q.id}><td>{q.quotation_number}</td><td className="mono">{q.customer_id}</td><td>Rev.{q.current_revision}</td><td><span className="status">{q.status}</span></td><td>{q.total_amount} {q.currency_code}</td></tr>)}</tbody></table></div></section>
 <section className="panel"><h2>Sales Orders</h2><div className="table-wrap"><table><thead><tr><th>SO</th><th>Source QT</th><th>Status</th><th></th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.order_number}</td><td>{o.source_quotation_id?"Rev."+o.source_quotation_revision:"Direct"}</td><td><span className="status">{o.status}</span></td><td><button type="button" onClick={()=>choose(o.id)}>Fulfillment</button></td></tr>)}</tbody></table></div></section>
 {selected&&<section className="panel"><h2>Reservation & Fulfillment</h2><div className="table-wrap"><table><thead><tr><th>Line</th><th>Ordered</th><th>Reserved</th><th>Delivered</th><th>Returned</th></tr></thead><tbody>{lines.map(x=><tr key={x.id}><td>{x.line_number}</td><td>{x.ordered_quantity}</td><td>{x.reserved_quantity}</td><td>{x.delivered_quantity}</td><td>{x.returned_quantity}</td></tr>)}</tbody></table></div><form className="login-card" onSubmit={e=>{e.preventDefault();void movement("reserve")}}><label>Location ID<input required value={location} onChange={e=>setLocation(e.target.value)}/></label><label>SO line<select required value={line} onChange={e=>setLine(e.target.value)}><option value="">Select line</option>{lines.map(x=><option key={x.id} value={x.id}>Line {x.line_number}</option>)}</select></label><label>Quantity<input required inputMode="decimal" value={qty} onChange={e=>setQty(e.target.value)}/></label><div><button className="button" type="submit">Reserve</button> <button type="button" onClick={()=>void movement("deliveries")}>Post Delivery</button> <button type="button" onClick={()=>void movement("returns")}>Post Return</button></div></form></section>}
 </main>
}