"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {apiError,authHeaders,newIdempotencyKey} from "../inventory/client";
type Choice={id:string;sku?:string;code?:string;name:string;legal_entity_id?:string;is_customer?:boolean};
type Q={id:string;quotation_number:string;customer_id:string;status:string;current_revision:number;total_amount:string;currency_code:string};
type O={id:string;order_number:string;status:string;source_quotation_id:string;source_quotation_revision:number};
type L={id:string;line_number:number;ordered_quantity:string;reserved_quantity:string;delivered_quantity:string;returned_quantity:string};
export default function Sales(){
 const [quotes,setQuotes]=useState<Q[]>([]),[orders,setOrders]=useState<O[]>([]),[lines,setLines]=useState<L[]>([]),[products,setProducts]=useState<Choice[]>([]),[units,setUnits]=useState<Choice[]>([]),[customers,setCustomers]=useState<Choice[]>([]),[entities,setEntities]=useState<Choice[]>([]),[locations,setLocations]=useState<Choice[]>([]);
 const [selected,setSelected]=useState(""),[location,setLocation]=useState(""),[line,setLine]=useState(""),[qty,setQty]=useState("");
 const [error,setError]=useState(""),[message,setMessage]=useState(""),[entity,setEntity]=useState(""),[customer,setCustomer]=useState(""),[product,setProduct]=useState(""),[unit,setUnit]=useState(""),[quoteQty,setQuoteQty]=useState("1"),[price,setPrice]=useState("0");const base=process.env.NEXT_PUBLIC_API_URL??"";
 const load=useCallback(async ()=>{const h=authHeaders();if(!h){setError("กรุณาเข้าสู่ระบบ");return}const [q,o,p,u,b,org,l]=await Promise.all([fetch(base+"/api/v1/sales/quotations",{headers:h}),fetch(base+"/api/v1/sales/orders",{headers:h}),fetch(base+"/api/v1/products",{headers:h}),fetch(base+"/api/v1/units",{headers:h}),fetch(base+"/api/v1/partners",{headers:h}),fetch(base+"/api/v1/organization",{headers:h}),fetch(base+"/api/v1/locations",{headers:h})]);if(!q.ok||!o.ok||!p.ok||!u.ok||!b.ok||!org.ok||!l.ok){setError("โหลด Sales master data ไม่สำเร็จ");return}setQuotes((await q.json()).data);setOrders((await o.json()).data);setProducts((await p.json()).data);setUnits((await u.json()).data);setCustomers(((await b.json()).data as Choice[]).filter(x=>x.is_customer));setEntities((await org.json()).data.legal_entities);setLocations((await l.json()).data)},[base]);
 useEffect(()=>{queueMicrotask(load)},[load]);

 async function createQuote(e:FormEvent){e.preventDefault();const h=authHeaders();if(!h)return;const r=await fetch(base+"/api/v1/sales/quotations",{method:"POST",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({legal_entity_id:entity,customer_id:customer,currency_code:"THB",lines:[{product_id:product,unit_id:unit,quantity:quoteQty,unit_price:price}]})});if(!r.ok){setError(await apiError(r));return}setMessage("Quotation created");await load()}
 async function quoteAction(id:string,action:"send"|"accept"){const h=authHeaders();if(!h)return;const r=await fetch(base+`/api/v1/sales/quotations/${id}/${action}`,{method:"POST",headers:{...h,...(action==="accept"?{"Content-Type":"application/json"}:{})},body:action==="accept"?JSON.stringify({accepted_by:"ERP Web"}):undefined});if(!r.ok){setError(await apiError(r));return}setMessage(action==="accept"?"Quotation accepted and Sales Order created":"Quotation sent");await load()}
 async function orderAction(id:string,action:"confirm"|"release-reservations"|"cancel"){const h=authHeaders();if(!h)return;const r=await fetch(base+`/api/v1/sales/orders/${id}/${action}`,{method:"POST",headers:h});if(!r.ok){setError(await apiError(r));return}setMessage(`Order ${action} complete`);await load()}
 async function choose(id:string){setSelected(id);const h=authHeaders();if(!h)return;const r=await fetch(base+"/api/v1/sales/orders/"+id+"/lines",{headers:h});if(!r.ok){setError(await apiError(r));return}setLines((await r.json()).data)}
 async function movement(kind:"reserve"|"deliveries"|"returns"){setError("");setMessage("");const h=authHeaders();if(!h||!selected||!line)return;const headers:Record<string,string>={...h,"Content-Type":"application/json"};if(kind!=="reserve")headers["Idempotency-Key"]=newIdempotencyKey(kind);const r=await fetch(base+"/api/v1/sales/orders/"+selected+"/"+kind,{method:"POST",headers,body:JSON.stringify({location_id:location,lines:[{sales_order_line_id:line,quantity:qty}]})});if(!r.ok){setError(await apiError(r));return}setMessage(kind==="reserve"?"Stock reserved":kind==="deliveries"?"Delivery posted":"Sales return posted");await load();await choose(selected)}
 return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">Sales & CRM</p><h1>Sales operations</h1><p>Quotation acceptance is traceable to an exact revision. Reservation changes availability only; delivery and return commit physical stock through Inventory.</p></div><Link className="button secondary" href="/crm">Open CRM pipeline</Link></div><div className="metrics"><div className="metric"><span>Quotations</span><strong>{quotes.length}</strong></div><div className="metric"><span>Sales Orders</span><strong>{orders.length}</strong></div><div className="metric"><span>Selected order</span><strong>{selected?"Open":"—"}</strong></div></div>{error&&<p className="error" role="alert">{error}</p>}{message&&<p aria-live="polite">{message}</p>}
 <form className="inline-form" onSubmit={createQuote}><select required value={entity} onChange={e=>setEntity(e.target.value)}><option value="">Legal entity</option>{entities.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><select required value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Customer</option>{customers.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><select required value={product} onChange={e=>setProduct(e.target.value)}><option value="">Product</option>{products.map(x=><option key={x.id} value={x.id}>{x.sku} · {x.name}</option>)}</select><select required value={unit} onChange={e=>setUnit(e.target.value)}><option value="">Unit</option>{units.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><input required type="number" min="0.000001" step="any" value={quoteQty} onChange={e=>setQuoteQty(e.target.value)} placeholder="Qty"/><input required type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Unit price"/><button className="button">Create quotation</button></form>\n <section className="panel"><div className="section-head"><h2>Quotation Pipeline</h2><Link href="/crm">CRM</Link></div><div className="table-wrap"><table><thead><tr><th>QT</th><th>Customer</th><th>Revision</th><th>Status</th><th>Total</th><th>Actions</th></tr></thead><tbody>{quotes.map(q=><tr key={q.id}><td>{q.quotation_number}</td><td className="mono">{q.customer_id}</td><td>Rev.{q.current_revision}</td><td><span className="status">{q.status}</span></td><td>{q.total_amount} {q.currency_code}</td><td>{q.status==="DRAFT"&&<button type="button" onClick={()=>void quoteAction(q.id,"send")}>Send</button>} {q.status==="SENT"&&<button type="button" onClick={()=>void quoteAction(q.id,"accept")}>Accept</button>}</td></tr>)}</tbody></table></div></section>
 <section className="panel"><h2>Sales Orders</h2><div className="table-wrap"><table><thead><tr><th>SO</th><th>Source QT</th><th>Status</th><th></th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.order_number}</td><td>{o.source_quotation_id?"Rev."+o.source_quotation_revision:"Direct"}</td><td><span className="status">{o.status}</span></td><td><button type="button" onClick={()=>choose(o.id)}>Fulfillment</button> {o.status==="DRAFT"&&<button type="button" onClick={()=>void orderAction(o.id,"confirm")}>Confirm</button>} {o.status!=="CANCELLED"&&<button type="button" onClick={()=>void orderAction(o.id,"cancel")}>Cancel</button>}</td></tr>)}</tbody></table></div></section>
 {selected&&<section className="panel"><h2>Reservation & Fulfillment</h2><div className="table-wrap"><table><thead><tr><th>Line</th><th>Ordered</th><th>Reserved</th><th>Delivered</th><th>Returned</th></tr></thead><tbody>{lines.map(x=><tr key={x.id}><td>{x.line_number}</td><td>{x.ordered_quantity}</td><td>{x.reserved_quantity}</td><td>{x.delivered_quantity}</td><td>{x.returned_quantity}</td></tr>)}</tbody></table></div><form className="login-card" onSubmit={e=>{e.preventDefault();void movement("reserve")}}><label>Location<select required value={location} onChange={e=>setLocation(e.target.value)}><option value="">Select location</option>{locations.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>SO line<select required value={line} onChange={e=>setLine(e.target.value)}><option value="">Select line</option>{lines.map(x=><option key={x.id} value={x.id}>Line {x.line_number}</option>)}</select></label><label>Quantity<input required inputMode="decimal" value={qty} onChange={e=>setQty(e.target.value)}/></label><div><button className="button" type="submit">Reserve</button> <button type="button" onClick={()=>void movement("deliveries")}>Post Delivery</button> <button type="button" onClick={()=>void movement("returns")}>Post Return</button></div></form></section>}
 </main>
}