"use client";
import Link from "next/link";import {useEffect,useState} from "react";import {apiError,authHeaders} from "../inventory/client";
type User={id:string;email:string;display_name:string;membership_status:string;roles:string[]};
type Role={id:string;code:string;name:string;permissions:string[]};
type Audit={id:string;occurred_at:string;action:string;target_type:string|null;result:string;request_id:string};
export default function Admin(){const [users,setUsers]=useState<User[]>([]),[roles,setRoles]=useState<Role[]>([]),[audit,setAudit]=useState<Audit[]>([]),[error,setError]=useState("");
useEffect(()=>{queueMicrotask(async()=>{const h=authHeaders();if(!h){setError("กรุณาเข้าสู่ระบบ");return}const base=process.env.NEXT_PUBLIC_API_URL??"";
for(const [path,setter] of [["users",setUsers],["roles",setRoles],["audit",setAudit]] as const){const r=await fetch(`${base}/api/v1/admin/${path}`,{headers:h});if(!r.ok){setError(await apiError(r));return}setter((await r.json()).data)}})},[]);
return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">PLATFORM · ADMINISTRATION</p><h1>Users, Roles & Audit</h1><p>Tenant-scoped security administration and immutable audit evidence. Server permissions remain authoritative.</p></div><Link className="button secondary" href="/">Operations</Link></div>{error&&<div className="state error">{error}</div>}
<div className="split"><section className="panel"><div className="panel-head"><h2>Users</h2><span className="badge">{users.length}</span></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Status</th><th>Roles</th></tr></thead><tbody>{users.map(x=><tr key={x.id}><td><strong>{x.display_name}</strong><small>{x.email}</small></td><td><span className="badge">{x.membership_status}</span></td><td>{x.roles.join(", ")||"—"}</td></tr>)}</tbody></table></div></section>
<section className="panel"><div className="panel-head"><h2>Roles</h2><span className="badge">{roles.length}</span></div><div className="table-wrap"><table><thead><tr><th>Role</th><th>Permissions</th></tr></thead><tbody>{roles.map(x=><tr key={x.id}><td><strong>{x.name}</strong><small className="mono">{x.code}</small></td><td><small>{x.permissions.join(", ")||"—"}</small></td></tr>)}</tbody></table></div></section></div>
<section className="panel" style={{marginTop:20}}><div className="panel-head"><h2>Audit trail</h2><span className="badge">{audit.length}</span></div><div className="table-wrap"><table><thead><tr><th>Time</th><th>Action</th><th>Target</th><th>Result</th><th>Request</th></tr></thead><tbody>{audit.map(x=><tr key={x.id}><td>{new Date(x.occurred_at).toLocaleString()}</td><td className="mono">{x.action}</td><td>{x.target_type??"—"}</td><td><span className="badge">{x.result}</span></td><td><small className="mono">{x.request_id}</small></td></tr>)}</tbody></table></div></section></main>}
