"use client";
import Link from "next/link";import {FormEvent,useEffect,useState} from "react";import {apiError,authHeaders} from "../client";
type Row={id:string;product_id:string;sku:string;product_name:string;location_id:string;location_code:string;warehouse_code:string;reorder_point:string;target_quantity:string;on_hand:string;suggested_quantity:string;needs_reorder:boolean};
type Product={id:string;sku:string;name:string};type Location={id:string;code:string;name:string};
export default function Reorder(){const [rows,setRows]=useState<Row[]>([]);const [products,setProducts]=useState<Product[]>([]);const [locations,setLocations]=useState<Location[]>([]);const [product,setProduct]=useState("");const [location,setLocation]=useState("");const [point,setPoint]=useState("");const [target,setTarget]=useState("");const [error,setError]=useState("");
async function load(){const h=authHeaders();if(!h)return;const [r,p,l]=await Promise.all([fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/inventory/operations/reorder`,{headers:h}),fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/products?status=ACTIVE&limit=200&sort=sku`,{headers:h}),fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/locations`,{headers:h})]);if(r.ok)setRows((await r.json()).data as Row[]);if(p.ok)setProducts((await p.json()).data as Product[]);if(l.ok)setLocations((await l.json()).data as Location[])}
useEffect(()=>{queueMicrotask(load)},[]);
async function save(e:FormEvent){e.preventDefault();setError("");const h=authHeaders();if(!h)return;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/inventory/operations/reorder-policies`,{method:"PUT",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({product_id:product,location_id:location,reorder_point:point,target_quantity:target,is_active:true})});if(!r.ok){setError(await apiError(r));return}setPoint("");setTarget("");await load()}
return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">INVENTORY · REORDER</p><h1>Reorder Signals</h1><p>Actionable replenishment signals only. This phase does not create Purchase Orders.</p></div><Link className="button secondary" href="/inventory/operations">Operations</Link></div>
<form className="inline-form" onSubmit={save}><select required value={product} onChange={e=>setProduct(e.target.value)}><option value="">Product</option>{products.map(x=><option key={x.id} value={x.id}>{x.sku} · {x.name}</option>)}</select><select required value={location} onChange={e=>setLocation(e.target.value)}><option value="">Location</option>{locations.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><input required inputMode="decimal" value={point} onChange={e=>setPoint(e.target.value)} placeholder="Reorder point"/><input required inputMode="decimal" value={target} onChange={e=>setTarget(e.target.value)} placeholder="Target"/><button className="button">Save policy</button></form>{error&&<div className="state error">{error}</div>}
<div className="table-wrap"><table><thead><tr><th>Status</th><th>SKU</th><th>Location</th><th>On hand</th><th>Reorder point</th><th>Target</th><th>Suggested</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><span className={"badge "+(x.needs_reorder?"attention":"")}>{x.needs_reorder?"REORDER":"OK"}</span></td><td><strong>{x.sku}</strong><small>{x.product_name}</small></td><td>{x.warehouse_code} / {x.location_code}</td><td className="quantity">{x.on_hand}</td><td className="quantity">{x.reorder_point}</td><td className="quantity">{x.target_quantity}</td><td className="quantity">{x.suggested_quantity}</td></tr>)}</tbody></table></div></main>}