"use client";
import Link from "next/link";import {FormEvent,useEffect,useState} from "react";import {apiError,authHeaders} from "../inventory/client";
type Partner={id:string;code:string;name:string;legal_name:string|null;tax_id:string|null;is_customer:boolean;is_supplier:boolean;status:string};
export default function Partners(){const [rows,setRows]=useState<Partner[]>([]);const [code,setCode]=useState("");const [name,setName]=useState("");const [customer,setCustomer]=useState(true);const [supplier,setSupplier]=useState(false);const [selected,setSelected]=useState<Partner|null>(null);const [detail,setDetail]=useState<{contacts:Array<{id:string;name:string;email:string|null;phone:string|null}>;addresses:Array<{id:string;address_type:string;line1:string;province:string|null}>}|null>(null);const [contactName,setContactName]=useState(""),[contactEmail,setContactEmail]=useState(""),[addressLine,setAddressLine]=useState("");const [error,setError]=useState(""),[editing,setEditing]=useState<Partner|null>(null);
async function load(){const h=authHeaders();if(!h){setError("กรุณาเข้าสู่ระบบ");return}const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/partners`,{headers:h});if(!r.ok){setError(await apiError(r));return}setRows((await r.json()).data)}
useEffect(()=>{queueMicrotask(load)},[]);
async function open(p:Partner){const h=authHeaders();if(!h)return;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/partners/${p.id}`,{headers:h});if(!r.ok){setError(await apiError(r));return}const b=await r.json();setSelected(p);setDetail(b.data)}
async function addContact(e:FormEvent){e.preventDefault();if(!selected)return;const h=authHeaders();if(!h)return;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/partners/${selected.id}/contacts`,{method:"POST",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({name:contactName,email:contactEmail||null,is_primary:false})});if(!r.ok){setError(await apiError(r));return}setContactName("");setContactEmail("");await open(selected)}
async function addAddress(e:FormEvent){e.preventDefault();if(!selected)return;const h=authHeaders();if(!h)return;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/partners/${selected.id}/addresses`,{method:"POST",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({address_type:"OFFICE",line1:addressLine,country_code:"TH",is_primary:false})});if(!r.ok){setError(await apiError(r));return}setAddressLine("");await open(selected)}
function edit(p:Partner){setEditing(p);setCode(p.code);setName(p.name);setCustomer(p.is_customer);setSupplier(p.is_supplier);setError("")}
function reset(){setEditing(null);setCode("");setName("");setCustomer(true);setSupplier(false)}
async function archive(id:string){const h=authHeaders();if(!h||!confirm("Archive this partner?"))return;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/partners/${id}/archive`,{method:"POST",headers:h});if(!r.ok){setError(await apiError(r));return}if(selected?.id===id){setSelected(null);setDetail(null)}await load()}
async function create(e:FormEvent){e.preventDefault();setError("");const h=authHeaders();if(!h)return;const url=editing?`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/partners/${editing.id}`:`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/partners`;const r=await fetch(url,{method:editing?"PUT":"POST",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({code,name,is_customer:customer,is_supplier:supplier})});if(!r.ok){setError(await apiError(r));return}reset();await load()}
return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">RELATIONSHIPS · PARTNERS</p><h1>Business Partners</h1><p>One tenant-safe identity may be a customer, supplier or both.</p></div><Link className="button secondary" href="/crm">CRM</Link></div>
<form className="inline-form" onSubmit={create}><input required value={code} onChange={e=>setCode(e.target.value)} placeholder="Partner code"/><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Name"/><label><input type="checkbox" checked={customer} onChange={e=>setCustomer(e.target.checked)}/> Customer</label><label><input type="checkbox" checked={supplier} onChange={e=>setSupplier(e.target.checked)}/> Supplier</label><button className="button">{editing?"Save partner":"Create partner"}</button>{editing&&<button type="button" className="button secondary" onClick={reset}>Cancel</button>}</form>{error&&<div className="state error">{error}</div>}
<div className="table-wrap"><table><thead><tr><th>Code</th><th>Name</th><th>Roles</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.code}</strong></td><td>{x.name}</td><td>{[x.is_customer&&"Customer",x.is_supplier&&"Supplier"].filter(Boolean).join(" · ")}</td><td><span className="badge">{x.status}</span></td><td><button type="button" onClick={()=>void open(x)}>Details</button> {x.status==="ACTIVE"&&<><button type="button" onClick={()=>edit(x)}>Edit</button> <button type="button" onClick={()=>void archive(x.id)}>Archive</button></>}</td></tr>)}</tbody></table></div>{selected&&detail&&<section className="panel"><div className="panel-head"><h2>{selected.code} · {selected.name}</h2><button type="button" onClick={()=>{setSelected(null);setDetail(null)}}>Close</button></div><div className="split"><div><h3>Contacts</h3><form className="inline-form" onSubmit={addContact}><input required value={contactName} onChange={e=>setContactName(e.target.value)} placeholder="Contact name"/><input type="email" value={contactEmail} onChange={e=>setContactEmail(e.target.value)} placeholder="Email"/><button className="button">Add contact</button></form>{detail.contacts.map(x=><p key={x.id}>{x.name} · {x.email??x.phone??"—"}</p>)}</div><div><h3>Addresses</h3><form className="inline-form" onSubmit={addAddress}><input required value={addressLine} onChange={e=>setAddressLine(e.target.value)} placeholder="Office address"/><button className="button">Add address</button></form>{detail.addresses.map(x=><p key={x.id}>{x.address_type} · {x.line1}{x.province?` · ${x.province}`:""}</p>)}</div></div></section>}</main>}