"use client";
import Link from "next/link";import {FormEvent,useEffect,useState} from "react";import {apiError,authHeaders} from "../inventory/client";
type Partner={id:string;code:string;name:string;legal_name:string|null;tax_id:string|null;is_customer:boolean;is_supplier:boolean;status:string};
export default function Partners(){const [rows,setRows]=useState<Partner[]>([]);const [code,setCode]=useState("");const [name,setName]=useState("");const [customer,setCustomer]=useState(true);const [supplier,setSupplier]=useState(false);const [error,setError]=useState("");
async function load(){const h=authHeaders();if(!h){setError("กรุณาเข้าสู่ระบบ");return}const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/partners`,{headers:h});if(!r.ok){setError(await apiError(r));return}setRows((await r.json()).data)}
useEffect(()=>{queueMicrotask(load)},[]);
async function create(e:FormEvent){e.preventDefault();setError("");const h=authHeaders();if(!h)return;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL??""}/api/v1/partners`,{method:"POST",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({code,name,is_customer:customer,is_supplier:supplier})});if(!r.ok){setError(await apiError(r));return}setCode("");setName("");await load()}
return <main className="erp-main"><div className="page-head"><div><p className="eyebrow">RELATIONSHIPS · PARTNERS</p><h1>Business Partners</h1><p>One tenant-safe identity may be a customer, supplier or both.</p></div><Link className="button secondary" href="/crm">CRM</Link></div>
<form className="inline-form" onSubmit={create}><input required value={code} onChange={e=>setCode(e.target.value)} placeholder="Partner code"/><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Name"/><label><input type="checkbox" checked={customer} onChange={e=>setCustomer(e.target.checked)}/> Customer</label><label><input type="checkbox" checked={supplier} onChange={e=>setSupplier(e.target.checked)}/> Supplier</label><button className="button">Create partner</button></form>{error&&<div className="state error">{error}</div>}
<div className="table-wrap"><table><thead><tr><th>Code</th><th>Name</th><th>Roles</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.code}</strong></td><td>{x.name}</td><td>{[x.is_customer&&"Customer",x.is_supplier&&"Supplier"].filter(Boolean).join(" · ")}</td><td><span className="badge">{x.status}</span></td></tr>)}</tbody></table></div></main>}